# docker-compose.yml
version: '3.8'
services:
  claude-code-proxy:
    build: .
    ports:
      - "3001:3001"
      - "5173:5173"
    volumes:
      - ./data:/app/data
      - ./config.yaml:/app/config.yaml:ro  # Mount config file
    environment:
      - ANTHROPIC_FORWARD_URL=https://api.anthropic.com
      - PORT=3001
      - WEB_PORT=5173
      - DB_PATH=/app/data/requests.db
